branch-defaults:
  default:
    environment: feeds-service-dev
    group_suffix: null
global:
  application_name: feeds_service
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-east-1
  profile: eb-cli
  sc: null
